version: '3.3'
services:
  dev:
    container_name: crypto_backend
    image: crypto_backend:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - backend-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  mongodb:
    image : mongo:latest
    container_name: crypto_mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - backend-network
    restart: always
networks:
    backend-network:
      driver: bridge