---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portfolio
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./helm/portfolio_backend
      sourceRef:
        kind: GitRepository
        name: portfolio
  interval: 10m0s

